import matplotlib as mpl
import matplotlib.pyplot as plt


def init_mpl(
    plot_type="line", dpi=200, figsize=(5.31, 3.99), grid=False, **custom_params
):
    """Updates matplotlib styling"""
    graph_params = line_params if plot_type == "line" else scatter_params
    mpl.rcParams.update(
        {
            **{"figure.dpi": dpi, "figure.figsize": figsize, "axes.grid": grid},
            **figure_params,
            **graph_params,
            **custom_params,
        }
    )


line_params = {
    # 'alpha': 1.0,
    # 'color': 'k',  # Should get updated according to
    "lines.linestyle": "-",
    "lines.linewidth": 1.25,
    "lines.marker": None,
    "lines.markersize": 0.0,
}

scatter_params = {
    # 'alpha': 1.0,
    # 'color': 'k',  # Might cycle through marker colours
    "lines.linestyle": "None",
    # 'marker': 'o',  # Might want to cycle through marker styles too
    # 'markeredgecolor': 'k',
    "lines.markeredgewidth": 0.5,
    # 'markerfacecolor': (1.0, 1.0, 1.0, 0.4),  # Include some opacity in marker colour
    "lines.markersize": 7.0,
}

axes_linewidth = 1.0
major_tick = 0.5
minor_tick = 0.4
top_right_spines = False
figure_params = {
    "font.family": "Roboto Light",
    "font.size": 10.0,
    "figure.subplot.top": 0.95,  # Position of graph top
    "figure.subplot.bottom": 0.15,  # Position of graph bottom
    "figure.dpi": 100,
    # "mathtext.fontset": "custom",
    # "mathtext.rm": "cmr10",
    "grid.alpha": 0.5,
    "grid.color": "#b0b0b0",
    "grid.linestyle": "-",
    "grid.linewidth": minor_tick,
    "axes.grid.axis": "both",
    "axes.grid.which": "major",
    "axes.labelcolor": "k",
    "axes.labelpad": 8.0,
    "axes.labelsize": 10.0,
    "axes.labelweight": 10,
    "axes.linewidth": axes_linewidth,
    "axes.spines.right": top_right_spines,
    "axes.spines.top": top_right_spines,
    "xtick.alignment": "center",
    "xtick.bottom": True,
    "xtick.color": "k",
    "xtick.direction": "in",
    "xtick.labelbottom": True,
    "xtick.labelsize": 10.0,
    "xtick.labeltop": False,
    "xtick.major.bottom": True,
    "xtick.major.pad": 10.0,
    "xtick.major.size": 4.0,
    "xtick.major.top": top_right_spines,
    "xtick.major.width": major_tick,
    "xtick.minor.bottom": True,
    "xtick.minor.pad": 10.0,
    "xtick.minor.size": 2.0,
    "xtick.minor.top": top_right_spines,
    "xtick.minor.visible": False,
    "xtick.minor.width": minor_tick,
    "xtick.top": True,
    "ytick.alignment": "center_baseline",
    "ytick.color": "k",
    "ytick.direction": "in",
    "ytick.labelleft": True,
    "ytick.labelright": False,
    "ytick.labelsize": 10.0,
    "ytick.left": True,
    "ytick.major.left": True,
    "ytick.major.pad": 10.0,
    "ytick.major.right": top_right_spines,
    "ytick.major.size": 4.0,
    "ytick.major.width": major_tick,
    "ytick.minor.left": True,
    "ytick.minor.pad": 6.0,
    "ytick.minor.right": top_right_spines,
    "ytick.minor.size": 2.0,
    "ytick.minor.visible": False,
    "ytick.minor.width": minor_tick,
    "ytick.right": True,
}

# SETTING UP PARAMETERS TO BE CALLED ON
# Use namedtuple for readable access of parameters. Not worth creating
# entire class. The only downside is their immutable, which I don't think
# will effect this program. I might need to update the scatter/line_param
# dictionaries though.
import collections

Style = collections.namedtuple(
    "Style", "type params fig_option fig_styles axes_scales axes_invert"
)
graph_dict = {
    "line": Style(
        type="line",
        params=line_params,
        fig_option="linestyle",
        fig_styles=["-", "-.", "--", ":", "-", "-.", "--", ":"],
        axes_scales=("linear", "linear"),
        axes_invert=(False, False),
    ),
    "smooth line": Style(
        type="smooth line",
        params=line_params,
        fig_option="linestyle",
        fig_styles=["-", "-.", "--", ":", "-", "-.", "--", ":"],
        axes_scales=("linear", "linear"),
        axes_invert=(False, False),
    ),
    "Bode": Style(
        type="loglog",
        params=line_params,
        fig_option="linestyle",
        fig_styles=["-", "-.", "--", ":", "-", "-.", "--", ":"],
        axes_scales=("log", "log"),
        axes_invert=(False, False),
    ),
    "phase": Style(
        type="semilog",
        params=line_params,
        fig_option="linestyle",
        fig_styles=["-", "-.", "--", ":", "-", "-.", "--", ":"],
        axes_scales=("log", "linear"),
        axes_invert=(False, True),
    ),
    "scatter": Style(
        type="scatter",
        params=scatter_params,
        fig_option="marker",
        fig_styles=[
            "o",
            "^",
            "s",
            "D",
            "*",
            "P",
            "X",
            "v",
            "p",
            "|",
            "_",
            "8",
            ".",
            "x",
        ],
        axes_scales=("linear", "linear"),
        axes_invert=(False, False),
    ),
}

# Dictionary of available colourmaps (Matplotliv 2.2.2)
mpl_cmaps = {
    "viridis": "uniform",
    "plasma": "uniform",
    "inferno": "uniform",
    "magma": "uniform",
    "Greys": "sequential",
    "Purples": "sequential",
    "Blues": "sequential",
    "Greens": "sequential",
    "Oranges": "sequential",
    "Reds": "sequential",
    "YlOrBr": "sequential",
    "YlOrRd": "sequential",
    "OrRd": "sequential",
    "PuRd": "sequential",
    "RdPu": "sequential",
    "BuPu": "sequential",
    "GnBu": "sequential",
    "PuBu": "sequential",
    "YlGnBu": "sequential",
    "PuBuGn": "sequential",
    "BuGn": "sequential",
    "YlGn": "sequential",
    "binary": "sequential2",
    "gist_yarg": "sequential2",
    "gist_gray": "sequential2",
    "gray": "sequential2",
    "bone": "sequential2",
    "pink": "sequential2",
    "spring": "sequential2",
    "summer": "sequential2",
    "autumn": "sequential2",
    "winter": "sequential2",
    "cool": "sequential2",
    "Wistia": "sequential2",
    "hot": "sequential2",
    "afmhot": "sequential2",
    "gist_heat": "sequential2",
    "copper": "sequential2",
    "PiYG": "diverging",
    "PRGn": "diverging",
    "BrBG": "diverging",
    "PuOr": "diverging",
    "RdGy": "diverging",
    "RdBu": "diverging",
    "RdYlBu": "diverging",
    "RdYlGn": "diverging",
    "Spectral": "diverging",
    "coolwarm": "diverging",
    "bwr": "diverging",
    "seismic": "diverging",
    "Pastel1": "qualitative",
    "Pastel2": "qualitative",
    "Paired": "qualitative",
    "Accent": "qualitative",
    "Dark2": "qualitative",
    "Set1": "qualitative",
    "Set2": "qualitative",
    "Set3": "qualitative",
    "tab10": "qualitative",
    "tab20": "qualitative",
    "tab20b": "qualitative",
    "tab20c": "qualitative",
    "flag": "miscellaneous",
    "prism": "miscellaneous",
    "ocean": "miscellaneous",
    "gist_earth": "miscellaneous",
    "terrain": "miscellaneous",
    "gist_stern": "miscellaneous",
    "gnuplot": "miscellaneous",
    "gnuplot2": "miscellaneous",
    "CMRmap": "miscellaneous",
    "cubehelix": "miscellaneous",
    "brg": "miscellaneous",
    "hsv": "miscellaneous",
    "gist_rainbow": "miscellaneous",
    "rainbow": "miscellaneous",
    "jet": "miscellaneous",
    "nipy_spectral": "miscellaneous",
    "gist_ncar": "miscellaneous",
}

default_params = {
    "_internal.classic_mode": False,
    "agg.path.chunksize": 0,
    "animation.avconv_args": [],
    "animation.avconv_path": "avconv",
    "animation.bitrate": -1,
    "animation.codec": "h264",
    "animation.convert_args": [],
    "animation.convert_path": "convert",
    "animation.embed_limit": 20.0,
    "animation.ffmpeg_args": [],
    "animation.ffmpeg_path": "ffmpeg",
    "animation.frame_format": "png",
    "animation.html": "none",
    "animation.html_args": [],
    "animation.writer": "ffmpeg",
    "axes.autolimit_mode": "data",
    "axes.axisbelow": "line",
    "axes.edgecolor": "k",
    "axes.facecolor": "w",
    "axes.formatter.limits": [-7, 7],
    "axes.formatter.min_exponent": 0,
    "axes.formatter.offset_threshold": 4,
    "axes.formatter.use_locale": False,
    "axes.formatter.use_mathtext": False,
    "axes.formatter.useoffset": True,
    "axes.grid": True,
    "axes.grid.axis": "both",
    "axes.grid.which": "major",
    # "axes.hold": None,  # deprecated in mpl 3.0
    "axes.labelcolor": "k",
    "axes.labelpad": 8.0,
    "axes.labelsize": 15.0,
    "axes.labelweight": 10,
    "axes.linewidth": 1.75,
    "axes.spines.bottom": True,
    "axes.spines.left": True,
    "axes.spines.right": True,
    "axes.spines.top": True,
    "axes.titlepad": 6.0,
    "axes.titlesize": "large",
    "axes.titleweight": "normal",
    "axes.unicode_minus": True,
    "axes.xmargin": 0.05,
    "axes.ymargin": 0.05,
    "axes3d.grid": True,
    # "backend": "MacOSX",
    "backend.qt4": None,
    "backend.qt5": None,
    "backend_fallback": True,
    "boxplot.bootstrap": None,
    "boxplot.boxprops.color": "k",
    "boxplot.boxprops.linestyle": "-",
    "boxplot.boxprops.linewidth": 1.0,
    "boxplot.capprops.color": "k",
    "boxplot.capprops.linestyle": "-",
    "boxplot.capprops.linewidth": 1.0,
    "boxplot.flierprops.color": "k",
    "boxplot.flierprops.linestyle": "none",
    "boxplot.flierprops.linewidth": 1.0,
    "boxplot.flierprops.marker": "o",
    "boxplot.flierprops.markeredgecolor": "k",
    "boxplot.flierprops.markerfacecolor": "none",
    "boxplot.flierprops.markersize": 6.0,
    "boxplot.meanline": False,
    "boxplot.meanprops.color": "C2",
    "boxplot.meanprops.linestyle": "--",
    "boxplot.meanprops.linewidth": 1.0,
    "boxplot.meanprops.marker": "^",
    "boxplot.meanprops.markeredgecolor": "C2",
    "boxplot.meanprops.markerfacecolor": "C2",
    "boxplot.meanprops.markersize": 6.0,
    "boxplot.medianprops.color": "C1",
    "boxplot.medianprops.linestyle": "-",
    "boxplot.medianprops.linewidth": 1.0,
    "boxplot.notch": False,
    "boxplot.patchartist": False,
    "boxplot.showbox": True,
    "boxplot.showcaps": True,
    "boxplot.showfliers": True,
    "boxplot.showmeans": False,
    "boxplot.vertical": True,
    "boxplot.whiskerprops.color": "k",
    "boxplot.whiskerprops.linestyle": "-",
    "boxplot.whiskerprops.linewidth": 1.0,
    "boxplot.whiskers": 1.5,
    "contour.corner_mask": True,
    "contour.negative_linestyle": "dashed",
    "datapath": "/Users/cal_lamont/miniconda3/envs/ucl/lib/python3.6/site-packages/matplotlib/mpl-data",
    "date.autoformatter.day": "%Y-%m-%d",
    "date.autoformatter.hour": "%m-%d %H",
    "date.autoformatter.microsecond": "%M:%S.%f",
    "date.autoformatter.minute": "%d %H:%M",
    "date.autoformatter.month": "%Y-%m",
    "date.autoformatter.second": "%H:%M:%S",
    "date.autoformatter.year": "%Y",
    "docstring.hardcopy": False,
    "errorbar.capsize": 0.0,
    # "examples.directory": "",  deprecated in mpl 3.0
    "figure.autolayout": False,
    "figure.constrained_layout.h_pad": 0.04167,
    "figure.constrained_layout.hspace": 0.02,
    "figure.constrained_layout.use": False,
    "figure.constrained_layout.w_pad": 0.04167,
    "figure.constrained_layout.wspace": 0.02,
    "figure.dpi": 100.0,
    "figure.edgecolor": "w",
    "figure.facecolor": "w",
    "figure.figsize": [6.4, 4.8],
    "figure.frameon": True,
    "figure.max_open_warning": 20,
    "figure.subplot.bottom": 0.175,
    "figure.subplot.hspace": 0.2,
    "figure.subplot.left": 0.175,
    "figure.subplot.right": 0.9,
    "figure.subplot.top": 0.95,
    "figure.subplot.wspace": 0.2,
    "figure.titlesize": "large",
    "figure.titleweight": "normal",
    "font.cursive": [
        "ms pmincho",
        "Apple Chancery",
        "Textile",
        "Zapf Chancery",
        "Sand",
        "Script MT",
        "Felipa",
        "cursive",
    ],
    "font.family": ["arial"],
    "font.fantasy": [
        "Comic Sans MS",
        "Chicago",
        "Charcoal",
        "ImpactWestern",
        "Humor Sans",
        "xkcd",
        "fantasy",
    ],
    "font.monospace": [
        "DejaVu Sans Mono",
        "Bitstream Vera Sans Mono",
        "Computer Modern Typewriter",
        "Andale Mono",
        "Nimbus Mono L",
        "Courier New",
        "Courier",
        "Fixed",
        "Terminal",
        "monospace",
    ],
    "font.sans-serif": [
        "arial",
        "DejaVu Sans",
        "Bitstream Vera Sans",
        "Computer Modern Sans Serif",
        "Lucida Grande",
        "Verdana",
        "Geneva",
        "Lucid",
        "Arial",
        "Helvetica",
        "Avant Garde",
        "sans-serif",
    ],
    "font.serif": [
        "DejaVu Serif",
        "Bitstream Vera Serif",
        "Computer Modern Roman",
        "New Century Schoolbook",
        "Century Schoolbook L",
        "Utopia",
        "ITC Bookman",
        "Bookman",
        "Nimbus Roman No9 L",
        "Times New Roman",
        "Times",
        "Palatino",
        "Charter",
        "serif",
    ],
    "font.size": 10.0,
    "font.stretch": "expanded",
    "font.style": "normal",
    "font.variant": "normal",
    "font.weight": "normal",
    "grid.alpha": 0.5,
    "grid.color": "#b0b0b0",
    "grid.linestyle": "-",
    "grid.linewidth": 0.5,
    "hatch.color": "k",
    "hatch.linewidth": 1.0,
    "hist.bins": 10,
    "image.aspect": "equal",
    "image.cmap": "viridis",
    "image.composite_image": True,
    "image.interpolation": "nearest",
    "image.lut": 256,
    "image.origin": "upper",
    "image.resample": True,
    "interactive": True,
    "keymap.all_axes": ["a"],
    "keymap.back": ["left", "c", "backspace"],
    "keymap.forward": ["right", "v"],
    "keymap.fullscreen": ["f", "ctrl+f"],
    "keymap.grid": ["g"],
    "keymap.grid_minor": ["G"],
    "keymap.home": ["h", "r", "home"],
    "keymap.pan": ["p"],
    "keymap.quit": ["ctrl+w", "cmd+w", "q"],
    "keymap.quit_all": ["W", "cmd+W", "Q"],
    "keymap.save": ["s", "ctrl+s"],
    "keymap.xscale": ["k", "L"],
    "keymap.yscale": ["l"],
    "keymap.zoom": ["o"],
    "legend.borderaxespad": 1.3,
    "legend.borderpad": 0.8,
    "legend.columnspacing": 2.0,
    "legend.edgecolor": "0.0",
    "legend.facecolor": "inherit",
    "legend.fancybox": False,
    "legend.fontsize": 8.0,
    "legend.framealpha": 1.0,
    "legend.frameon": True,
    "legend.handleheight": 0.7,
    "legend.handlelength": 2.0,
    "legend.handletextpad": 0.8,
    "legend.labelspacing": 0.7,
    "legend.loc": "best",
    "legend.markerscale": 1.0,
    "legend.numpoints": 1,
    "legend.scatterpoints": 1,
    "legend.shadow": False,
    "lines.antialiased": True,
    "lines.color": "C0",
    "lines.dash_capstyle": "butt",
    "lines.dash_joinstyle": "round",
    "lines.dashdot_pattern": [6.4, 1.6, 1.0, 1.6],
    "lines.dashed_pattern": [3.7, 1.6],
    "lines.dotted_pattern": [1.0, 1.65],
    "lines.linestyle": "-",
    "lines.linewidth": 2.0,
    "lines.marker": "None",
    "lines.markeredgewidth": 1.0,
    "lines.markersize": 0.0,
    "lines.scale_dashes": True,
    "lines.solid_capstyle": "projecting",
    "lines.solid_joinstyle": "round",
    "markers.fillstyle": "full",
    "mathtext.bf": "sans:bold",
    "mathtext.cal": "cursive",
    "mathtext.default": "it",
    "mathtext.fallback_to_cm": True,
    "mathtext.fontset": "dejavusans",
    "mathtext.it": "sans:italic",
    "mathtext.rm": "sans",
    "mathtext.sf": "sans",
    "mathtext.tt": "monospace",
    "patch.antialiased": True,
    "patch.edgecolor": "k",
    "patch.facecolor": "C0",
    "patch.force_edgecolor": False,
    "patch.linewidth": 1.0,
    "path.effects": [],
    "path.simplify": True,
    "path.simplify_threshold": 0.1111111111111111,
    "path.sketch": None,
    "path.snap": True,
    "pdf.compression": 6,
    "pdf.fonttype": 3,
    "pdf.inheritcolor": False,
    "pdf.use14corefonts": False,
    # "pgf.debug": False,  deprecated in mpl 3.0
    "pgf.preamble": [],
    "pgf.rcfonts": True,
    "pgf.texsystem": "xelatex",
    "polaraxes.grid": True,
    "ps.distiller.res": 6000,
    "ps.fonttype": 3,
    "ps.papersize": "letter",
    "ps.useafm": False,
    "ps.usedistiller": False,
    "savefig.bbox": None,
    "savefig.directory": "~",
    "savefig.dpi": "figure",
    "savefig.edgecolor": "w",
    "savefig.facecolor": "w",
    "savefig.format": "png",
    "savefig.frameon": True,
    "savefig.jpeg_quality": 95,
    "savefig.orientation": "portrait",
    "savefig.pad_inches": 0.1,
    "savefig.transparent": False,
    "scatter.marker": "o",
    "text.color": "k",
    "text.hinting": "auto",
    "text.hinting_factor": 8,
    "text.latex.preamble": [],
    "text.latex.preview": False,
    # "text.latex.unicode": False,  # deprecated in mpl 2.2
    "text.usetex": True,
    "timezone": "UTC",
    "tk.window_focus": False,
    "toolbar": "toolbar2",
    "verbose.fileo": "sys.stdout",
    "verbose.level": "silent",
    "webagg.address": "127.0.0.1",
    "webagg.open_in_browser": True,
    "webagg.port": 8988,
    "webagg.port_retries": 50,
    "xtick.alignment": "center",
    "xtick.bottom": True,
    "xtick.color": "k",
    "xtick.direction": "in",
    "xtick.labelbottom": True,
    "xtick.labelsize": 10.0,
    "xtick.labeltop": False,
    "xtick.major.bottom": True,
    "xtick.major.pad": 10.0,
    "xtick.major.size": 4.0,
    "xtick.major.top": True,
    "xtick.major.width": 1.0,
    "xtick.minor.bottom": True,
    "xtick.minor.pad": 10.0,
    "xtick.minor.size": 2.0,
    "xtick.minor.top": True,
    "xtick.minor.visible": False,
    "xtick.minor.width": 0.6,
    "xtick.top": True,
    "ytick.alignment": "center_baseline",
    "ytick.color": "k",
    "ytick.direction": "in",
    "ytick.labelleft": True,
    "ytick.labelright": False,
    "ytick.labelsize": 10.0,
    "ytick.left": True,
    "ytick.major.left": True,
    "ytick.major.pad": 10.0,
    "ytick.major.right": True,
    "ytick.major.size": 4.0,
    "ytick.major.width": 1.0,
    "ytick.minor.left": True,
    "ytick.minor.pad": 6.0,
    "ytick.minor.right": True,
    "ytick.minor.size": 2.0,
    "ytick.minor.visible": False,
    "ytick.minor.width": 0.6,
    "ytick.right": True,
}

# label_font = {'family': 'Garamond', 'weight': 1.0, 'size': 15.0}
# mpl.rcParams.update(default_params)
